---
title: "R Notebook"
output: html_notebook
---


```{r}
clean_country <- combined %>% 
  select(country) %>% 
  mutate(
    country = recode(country, "USA" = ("United States", "usa") )
  )
```

```{r}
clean_country <-combined %>% 
  mutate(country = case_when(
              country == "United States" ~ "USA",
              country == "usa" ~ "USA",
              country == "US" ~ "USA",
              TRUE ~ country)) %>% 
  count(country)
```

```{r}
# replacing "--" with NA
clean_country <- country_codes %>%
  mutate(country = replace(country, country ==  c("u s a", "U.s."), "usa"))

```


```{r}
pattern <- "[uU]nited] +[sSt]"

clean_country <- country_codes %>%
  str_replace(pattern, "USA")
```



```{r}
usa_list <- list(1, "a", TRUE, c(1, 2, 3))
```


```{r}
candyData['Q4: COUNTRY']=candyData['Q4: COUNTRY'].str.lower()
usa={'usa', 'murica', 'us', 'united states','america', 'u.s','u s','u.s.', 'u s a', 'unite states', 'united state'}
canadas={'canada', 'can'}
for element in candyData['Q4: COUNTRY']:
    if type(element) is not float:
        for u in usa:
            if u in element:
                candyData['Q4: COUNTRY'] = candyData['Q4: COUNTRY'].replace(element,'USA')
        for c in canadas:
            if c in element:
                candyData['Q4: COUNTRY'] = candyData['Q4: COUNTRY'].replace(element,'Canada')
    
for element in candyData['Q4: COUNTRY']:
    if type(element) is not float:
        if 'USA' not in element and 'Canada' not in element:
            candyData['Q4: COUNTRY'] = candyData['Q4: COUNTRY'].replace(element,np.NaN)

candyData = candyData[pd.notnull(candyData['Q4: COUNTRY'])]
candyData
```


```{r}
all_usa_names <- c("USAUSAUSA", "usas", "USAA", "USA? Hard to tell anymore..", "USA!!!!!!", "USA! USA!", "USA!", "USA USA USA!!!!", "USA USA USA USA",
                "USA USA USA", "USA (I think but it's an election year so who can really tell)", "USa", "uSA", "Units States", "United ststes", "united      ststes", "usa", "US", "Usa", "United States of America", "us", "united states", "United states", "Us", "U.S.", "U.S.A.", "united states of america", "America", "america", "u.s.", "Murica", "Unites States", "US of A", "United State", "USA! USA! USA!", "Merica", "The United States", "United Sates", "United Stated", "USSA", "'merica", "Ahem....Amerca", "N. America", "the best one - usa", "The United States of America", "	The Yoo Ess of Aaayyyyyy", "U S", "u s a", "U.s.", "u.s.a.", "Unied States", "unhinged states", "Unied States", "unite states", "United  States of America", "United staes", "United Statea", "united States", "UNited States", "United Statss", "United Stetes", "	united ststes", "United ststes", "Units States", "uSA", "USa", "USA (I think but it's an election year so who can really tell)", "USA USA USA", "USA USA USA USA", "USA USA USA!!!!", "USA!", "USA! USA!", "USA!!!!!!", "USA? Hard to tell anymore..", "USAA", "usas", "USAUSAUSA")
```

```{r}

country_convert_list <- c( "united states" = "usa", "united states of america" = "usa","america" = "usa","usa! usa! usa!" = "usa", "usa! usa! usa!" = "USA", "u.s." = "usa", 
                           "sub-canadian north usa... 'merica" = "usa", "usa of usa" = "usa", "the best one - usa" = "usa","murica" = "usa","^us$" = "usa", "usa of usa"= "usa",
                           "england" = "united kingdom","uk" = "united kingdom", "usaa." = "usa") 
candy_data_1$which_country_do_you_live_in <- str_replace_all(tolower(candy_data_1$which_country_do_you_live_in), country_convert_list)
```

```{r}
amended_country_codes<- country_codes %>% 
  mutate(
    country = if_else(country == 
              ("usa","The United States") "USA", country)
    
  )
```

```{r}
amended_country_codes %>% 
  group_by(country) %>% 
  summarise(
    n = n()
  )
```

```{r}
pattern <- "[(i?)united] [(i?)st]"

new_country <- country_codes$country %>%
  str_replace_all(pattern, "USA")

new_country
```

```{r}
# Replace US dud data
country_codes<- country_codes %>%
  mutate (country = str_replace(country, "USAUSAUSA|usas|USAA|USA? Hard to tell anymore..|USA!!!!!!|USA! USA!|USA!|USA USA USA!!!!|USA USA USA USA|USAUSAUSA|usas|USAA|USA? Hard to tell anymore..|USA!!!!!!|USA! USA!|USA!|USA USA USA!!!!|USA USA USA USA|USA USA USA|USa|uSA|Units States|United ststes|united      ststes|usa|US|Usa|United States of America|us|united states|United states|Us|U.S.|U.S.A.|united states of america|America|america|u.s.|Murica|Unites States|US of A|United State|USA! USA! USA!|Merica|The United States|United Sates|United Stated|USSA|Ahem....Amerca|N. America|the best one - usa|The United States of America|	The Yoo Ess of Aaayyyyyy|U S|u s a|U.s.|u.s.a.|Unied States|unhinged states|Unied States|unite states|United  States of America|United staes|United Statea|united States|UNited States|United Statss|United Stetes|	united ststes|United ststes|Units States|uSA|USa|USA USA USA|USA USA USA USA|USA USA USA!!!!|USA!|USA! USA!|USA!!!!!!|USA? Hard to tell anymore..|USAA|usas|USAUSAUSA|Trumpistan|Alaska|6
I pretend to be from Canada, but I am really from the usa.|	
Fear and Loathing|united ststes|usa of A|usa of usa|usa usa|usaa|usaA|usaA? Hard to tell anymore..|	
usaa.|usaA.|usad|usaSA", "W00P"))
```


```{r}
# Small Test
country_codes<- country_codes %>%
  mutate (country = str_replace_all(country, "USAUSAUSA|usas|1
'merica|USA! USA!", "usa"))
```

```{r}
# Count amended countries
count_countries <- country_codes %>% 
  group_by(country) %>% 
  summarise(
    n = n()
  )

```

```{r}
country_codes<- country_codes %>%
  mutate(country = str_to_lower(country)) 


country_codes2 <- country_codes %>% 
  group_by(country) %>% 
  summarise(
    n = n()
  )
```


```{r}

pattern <-"usausausa" , "usas" , "usaa" , "usa? hard to tell anymore.." , "usa!!!!!!" , "usa! usa!" , "usa!" , "usa usa usa!!!!" , "usa usa usa usa" , "usausausa" , "usas" , "usaa" , "usa? hard to tell anymore.." , "usa!!!!!!" , "usa! usa!" , "usa!" , "usa usa usa!!!!" , "usa usa usa usa" , "usa usa usa" , "usa" , "usa" , "units states" , "united ststes" , "united      ststes" , "usa" , "us" , "usa" , "united states of america" , "us" , "united states" , "united states" , "us" , "u.s." , "u.s.a." , "united states of america" , "america" , "america" , "u.s." , "murica" , "unites states" , "us of a" , "united state" , "usa! usa! usa!" , "merica" , "the united states" , "united sates" , "united stated" , "ussa" , "ahem....amerca" , "n. america" , "the best one - usa" , "the united states of america" , "	the yoo ess of aaayyyyyy" , "u s" , "u s a" , "u.s." , "u.s.a." , "unied states" , "unhinged states" , "unied states" , "unite states" , "united  states of america" , "united staes" , "united statea" , "united states" , "united states" , "united statss" , "united stetes" , "	united ststes" , "united ststes" , "units states" , "usa" , "usa" , "usa usa usa" , "usa usa usa usa" , "usa usa usa!!!!" , "usa!" , "usa! usa!" , "usa!!!!!!" , "usa? hard to tell anymore.." , "usaa" , "usas" , "usausausa" , "trumpistan" , "alaska" , "6
i pretend to be from canada, but i am really from the usa." , "	
fear and loathing" , "united ststes" , "usa of a" , "usa of usa" , "usa usa" , "usaa" , "usaa" , "usaa? hard to tell anymore.." , "	
usaa." , "usaa." , "usad" , "usasa"

country_codes<- country_codes %>%
  mutate(country = str_replace(country, pattern, "WOOP")) 

```

```{r}

pattern <-"[usausausa] [usas] [usaa]"

country_codes<- country_codes %>%
  mutate(country = str_replace(country, pattern, "WOOP")) 

country_codes2 <- country_codes %>% 
  group_by(country) %>% 
  summarise(
    n = n()
  )

```

```{r}
country_codes %>% 
  mutate(country = str_replace_all(country, pattern, "USA")) %>% 
  group_by(country)
```

```{r}
# Replace US dud data
country_codes<- country_codes %>%
  mutate (country = str_replace(country, "usausausa|usas|usaa|usa? hard to tell anymore..|usa!!!!!!|usa! usa!|usa!|usa usa usa!!!!|usa usa usa usa|usausausa|usas|usaa|usa? hard to tell anymore..|usa!!!!!!|usa! usa!|usa!|usa usa usa!!!!|usa usa usa usa|usa usa usa|usa|usa|units states|united ststes|united      ststes|usa|us|usa|united states of america|us|united states|united states|us|u.s.|u.s.a.|united states of america|america|america|u.s.|murica|unites states|us of a|united state|usa! usa! usa!|merica|the united states|united sates|united stated|ussa|ahem....amerca|n. america|the best one - usa|the united states of america|	the yoo ess of aaayyyyyy|u s|u s a|u.s.|u.s.a.|unied states|unhinged states|unied states|unite states|united  states of america|united staes|united statea|united states|united states|united statss|united stetes|	united ststes|united ststes|units states|usa|usa|usa usa usa|usa usa usa usa|usa usa usa!!!!|usa!|usa! usa!|usa!!!!!!|usa? hard to tell anymore..|usaa|usas|usausausa|trumpistan|alaska|6
i pretend to be from canada, but i am really from the usa.|	
fear and loathing|united ststes|usa of a|usa of usa|usa usa|usaa|usaa|usaa? hard to tell anymore..|	
usaa.|usaa.|usad|usasa", "W00P"))
```

```{r}
pattern <- c("'merica", "ahem....amerca", "america", "i pretend to be from canada, but i am really from the united states.","n. america", "sub-canadian north america... 'merica", "the best one - usa", "the united states", "the united states of america", "the yoo ess of aaayyyyyy", "trumpistan", "u s", "u s a", "u.s.", "u.s.a.", "unhinged states", "unied states", "unite states", "united  states of america", "united sates", "united staes", "united state", "united statea", "united stated", "united states", "united states of america", "united statss", "united stetes", "united ststes", "unites states", "units states", "us", "us of a", "usa", "usa (i think but it's an election year so who can really tell)", "usa usa usa", "usa usa usa usa", "usa usa usa!!!!", "usa!", "usa! usa!", "usa! usa! usa!", "usa!!!!!!", "usa? hard to tell anymore..", "usaa", "usas", "usausausa","ussa")
```


```{r}
# Group on amended code to check progress
country_codes_regrouped <- country_codes %>% 
  group_by(country2) %>% 
  summarise(
    n = n()
  )
```

```{r}
candy_ratings %>% ungroup() %>% 
  slice_max(MEH)
```

```{r}
# Using the candy_ratings table find the top for each rating type
candy_ratings[candy_ratings$DESPAIR == max(candy_ratings$DESPAIR),] 
candy_ratings[candy_ratings$JOY == max(candy_ratings$JOY),] 
candy_ratings[candy_ratings$MEH == max(candy_ratings$MEH),]
```

```{r}
# Using the candy_ratings table find the top for each rating type
candy_ratings<- drop_na(candy_ratings,MEH) %>% 
candy_ratings[candy_ratings$MEH == max(candy_ratings$MEH),]
```