---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```


Analysis questions
1. Which cake has the most cocoa in it?
2. For sponge cake, how many cups of ingredients are used in total?
3. How many ingredients are measured in teaspoons?
4. Which cake has the most unique ingredients?
5. Which ingredients are used only once?

```{r}
here()
cake_ingredients_join <- read_csv("../clean_data/cake_ingredients_join")
```


```{r}
#1. Which cake has the most cocoa in it?
question_1 <- cake_ingredients_join %>%
  filter(ingredient == "Cocoa") %>%
  arrange(desc(units)) %>%
  slice(1:3)
#the cake with the most coca in is One Bowl Chocolate with 10 tablespoons.
  
```

```{r}
#2. For sponge cake, how many cups of ingredients are used in total?
question_2 <- cake_ingredients_join %>%
  filter(cake == "Sponge",
         measure == "cup") %>%
  summarise(cup_total = n())
#There are a total of 10 cups of ingredients 
```

```{r}
#3. How many ingredients are measured in teaspoons?
question_3 <- cake_ingredients_join %>%
              drop_na() %>%
              group_by(ingredient) %>%
              filter(measure == "teaspoon") %>%
              summarise(measure = n())
#A total of 8 ingredeints are measured in teaspoons
```

```{r}
#4. Which cake has the most unique ingredients?
#I firstly need to remove the NAs to make this work. This is what I realised and changed in my clean data as this was not working. It kept saying 34 because it kept counting how many ingredients there are altogether but what I need to do is count the units because that will give the unique amount used by each cake.
question_4 <- cake_ingredients_join %>%
              drop_na() %>%
              group_by(cake) %>%
              distinct(units) %>%
              count(units) %>%
              summarise(n = n())%>%
              slice_max(n, n = 1)
              
```

```{r}
#5. Which ingredients are used only once?
question_5 <- cake_ingredients_join %>%
              drop_na() %>%
              group_by(ingredient) %>%
              distinct(units) %>%
              count(units) %>%
              summarise(n = n())%>%
              slice_min(n)
```



